### ISSUE TITLE
Agently的storage可以使用数据库么（mysql redis之类的）？好像只看到filestorage

### ISSUE THREAD

**Issue by duoduo369** [Maplemx/Agently#104]

**Comment by Maplemx** [comment]
可以参考/plugins/storage 文件夹里的插件格式进行开发者定制化添加

我正在用sqlite做一个新的可替换插件，下周末之前会发布出来，其他类型的数据库可以参考这个插件进行修改定制

**Comment by Maplemx** [comment]
hi, please check this commit see if this SQLite plugin can give some inspire about how to make other database plugins or not?

https://github.com/Maplemx/Agently/commit/5230bf15171d510020ae26ddcba4041b89c4b672
