### ISSUE TITLE
Does the output result of each workflow chunk support the streaming output of workflow.start?

### ISSUE THREAD

**Issue by Anionex** [Maplemx/Agently#137]
Does the output result of each workflow chunk support the streaming output of workflow.start?
how to do it?or i have to do it through web socket?

**Comment by Maplemx** [comment]
No, the workflow object can not support streaming generator right now.

But the agent object can support that using an event listener.

```python
import Agently
agent = Agently.create_agent()

@agent.on_event("delta")
def delta_handler(data):
    print(data)

agent.input("hi").start()
```

**Comment by Maplemx** [comment]
Read this to explore more: https://agently.tech/guides/agent_request/guide.html#_15
