### ISSUE TITLE
想要让LLM帮忙编写文档，编写过程需要借鉴知识库的相关内容，能不能指明一下开发方向

### ISSUE THREAD

**Issue by tankGe** [Maplemx/Agently#147]
我是一个项目经理，经常需要编写项目文档，看了Agently的介绍，觉得可以基于该框架定制一个文档编写助手，我的思路是这样的：用户输入文档编写需求，告诉LLM模型进行编写，过程中先从知识库检索相关内容，如果返回有则引用知识库内容，没有则使用互联网搜索或者LLM自身知识进行完善。基于上面的思路，能不能帮忙指明一下Agently的开发流程，不胜感激！

**Comment by Maplemx** [comment]
hello，可以通过构建处理工作流的方式进行处理

首先，构建第一个工作块：文档编写规划（`plan_doc_outline`），在这个工作块里，你可以让agent对象生成文档的基础目录、提纲、写作要求等信息，同时生成需要检索的信息要点；

然后，构建第二个工作块：信息检索（`query_info`），在这个工作块里，你可以选择将检索信息要点的需求进行向量化，然后从存储文档信息的知识库进行向量检索，获得返回的知识碎块；或者你也可以直接使用现成的知识库服务，比如AWS的https://aws.amazon.com/cn/bedrock/knowledge-bases/ 取出对应的知识碎块；当然，这一步也可以进一步细化成更复杂的工作流程，比如关键词切片，搜索，检索等；

接下来，构建第三个工作块：撰写文档（`awswer_question`），在这个工作块里，你需要将撰写要求和检索到的知识碎块一起传递给模型，然后让它分段撰写文档

最后，规划你的工作流，loop_with编写规划，然后检索+撰写组合

这是开发的基本思路，根据具体业务场景再进行调整

**Comment by tankGe** [comment]
> hello，可以通过构建处理工作流的方式进行处理
> 
> 首先，构建第一个工作块：文档编写规划（`plan_doc_outline`），在这个工作块里，你可以让agent对象生成文档的基础目录、提纲、写作要求等信息，同时生成需要检索的信息要点；
> 
> 然后，构建第二个工作块：信息检索（`query_info`），在这个工作块里，你可以选择将检索信息要点的需求进行向量化，然后从存储文档信息的知识库进行向量检索，获得返回的知识碎块；或者你也可以直接使用现成的知识库服务，比如AWS的https://aws.amazon.com/cn/bedrock/knowledge-bases/ 取出对应的知识碎块；当然，这一步也可以进一步细化成更复杂的工作流程，比如关键词切片，搜索，检索等；
> 
> 接下来，构建第三个工作块：撰写文档（`awswer_question`），在这个工作块里，你需要将撰写要求和检索到的知识碎块一起传递给模型，然后让它分段撰写文档
> 
> 最后，规划你的工作流，loop_with编写规划，然后检索+撰写组合
> 
> 这是开发的基本思路，根据具体业务场景再进行调整

感谢详细的指导
