### ISSUE TITLE
使用工具的时候可以取到中间过程的响应吗？

### ISSUE THREAD

**Issue by languanghao** [Maplemx/Agently#158]
1. 向agent注册获取当前时间的工具
2. 提问：今天天气怎么样
3. 预期效果：希望能够在 `output` 进行输出格式控制，如果没有成功调用tool，则返回“我不了这个问题”

目前看到确实大模型返回了一个可以解析的JSON格式
[Final Response]
 ```json
{
	"need_tool": false,
	"input_target_language": "中文",
	"tools_using": []
}
``` 
要怎么样才能取到 `need_tool` 这个字段的值？

**Comment by Maplemx** [comment]
使用监听器：

```python
def judgement_handler(data):
    pass

def tool_response_handler(data):
    pass

agent.add_event_listener("event:judgement", judgement_handler)
agent.add_event_listener("event:response", tool_response_handler)
```

**Comment by languanghao** [comment]
@Maplemx 感谢大佬，试了下，事件名称应该如下才对：

```
agent
        .add_event_listener("tool:judgement", judgement_handler)
        .add_event_listener("tool:response", tool_response_handler)
```

**Comment by Maplemx** [comment]
> @Maplemx 感谢大佬，试了下，事件名称应该如下才对：
> 
> ```
> agent
>         .add_event_listener("tool:judgement", judgement_handler)
>         .add_event_listener("tool:response", tool_response_handler)
> ```

啊，对的，typo了
