### ISSUE TITLE
SoT ToT 样例

### ISSUE THREAD

**Issue by yhyu13** [Maplemx/Agently#16]
> 通过这样的编排能力，你可以构建出复杂的行为链条，甚至可以在Agent实例内实现ToT（思维树）、SoT（思维骨架）这样的复杂思考方式。

有样例吗，谢谢？或者又那些推荐使用的py库来outofbox实现这些功能？

**Comment by Maplemx** [comment]
感谢关注！

9月会陆续做一些demo出来，方式上可以用work node里内置的worker来实现。

因为目前要做的工作比较多，比如追平nodejs 1.1.3提供的预置能力（比如流式请求切块），准备官网和文档，准备更多demo。

各种思维模式的show case也在逐步准备中。

**Comment by Maplemx** [comment]
可以查看Playground的各种案例了
