### ISSUE TITLE
希望支持国产开源大模型

### ISSUE THREAD

**Issue by weibo021** [Maplemx/Agently#21]
Baichuan2-13B、Baichuan2-7B
ChatGLM2-6B
Qwen-14B、Qwen-7B

**Comment by dafei2017** [comment]
ChatGLM2-6B

**Comment by whisky-12** [comment]
您好 ，请问现在最新的代码，支持国产模型吗，比如ChatGLM3

**Comment by Maplemx** [comment]
> 您好 ，请问现在最新的代码，支持国产模型吗，比如ChatGLM3

国产模型已经适配智谱GLM4和GLM3-turbo的线上版，以及百度文心4

如果想要自己本地启动模型，可以用其他开源项目转换成OpenAI格式API，再用OpenAI配置中提供的url修改指向本地的API来使用

**Comment by Maplemx** [comment]
请参考本案例：https://github.com/Maplemx/Agently/blob/main/playground/using_local_open_source_model_to_drive_agents.ipynb

**Comment by ZohnSun** [comment]
Ali:qwen?

**Comment by Maplemx** [comment]
> Ali:qwen?

using OAIClient then same as Kimi following this instruction: http://agently.cn/features/model_request.html#kimi
