### ISSUE TITLE
请问一下支持输入图片，对图片进行评价吗

### ISSUE THREAD

**Issue by wangpx0906** [Maplemx/Agently#30]

**Comment by Maplemx** [comment]
GPT 4v还没接入，插件理论上可行

**Comment by wangpx0906** [comment]
> GPT 4v还没接入，插件理论上可行

目前gpt-4-1106-vision-preview已经支持输入图片url对图像进行处理了，请问一下agently3.0什么时候可以支持gpt-4-1106-vision-preview

**Comment by Maplemx** [comment]
https://github.com/Maplemx/Agently/commit/c977614f6bb2bfd6c86b93910b772882b3f1102a

已经在此次提交中支持，发版pypi后关闭此issue

**Comment by wangpx0906** [comment]
> [c977614](https://github.com/Maplemx/Agently/commit/c977614f6bb2bfd6c86b93910b772882b3f1102a)
> 
> 已经在此次提交中支持，发版pypi后关闭此issue

感谢

**Comment by Maplemx** [comment]
使用方法：
```python
agent\
    .input("这是一张什么图？")\
    .files("https://pic1.zhimg.com/80/v2-3c051673fdafc3dfe0faa79ba5495f68_1440w.webp")\
    .output({
        "图片信息读取": ("String", "简要说明图片里包含的信息"),
        "图片解释": ("String", "解释你怎么理解这样图的含义"),
        "图片类型": ("String", "给这个图片做一个分类，比如生活照、广告、街道实景等"),
    })\
    .start("vision")
```

需要确保：
当前使用的模型为OpenAI系列模型；（即settings中，current_model为OpenAI）且您的API-KEY具有使用4-v-pre模型的权限
