### ISSUE TITLE
提两个bug修正的地方

### ISSUE THREAD

**Issue by aiwenForGit** [Maplemx/Agently#72]
1.yaml文件里面有中文会报错，
`Exception: [Agent Component: YAMLReader]: Error occured when read YAML from path './prompt.yaml'.
Error: 'gbk' codec can't decode byte 0xad in position 109: illegal multibyte sequence`
修正方法：open(path, "r", encoding="utf-8")，
![image](https://github.com/Maplemx/Agently/assets/241340/1b030e6b-a795-4d3d-be01-43579b01524e)

2.模型claude.py中如果要用到中转代理，设置下base_url，
![image](https://github.com/Maplemx/Agently/assets/241340/2d4a6076-dedd-4ddf-ae07-6a10227e8cae)

**Comment by Maplemx** [comment]
感谢指出，下次可以直接提交PR到dev分支，成为我们的contributor

**Comment by Maplemx** [comment]
1: https://github.com/Maplemx/Agently/commit/dc9e3707106c27d8b6171813d1d510a2ecdcfe07

2: https://github.com/Maplemx/Agently/commit/dcc9e04447bb825f79860266e3edcb8c2c8dddeb

Claude更换base_url的用法和OAIClient保持一致：

```python
.set_settings("current_model", "Claude")
.set_settings("model.Claude.url", "xxxxxxxxxxx")
```
url需要表达为`http://xxxxx.xxx/v1`

**Comment by Maplemx** [comment]
publish in v3.2.2.3
