### ISSUE TITLE
Missing function in docs

### ISSUE THREAD

**Issue by Undertone0809** [Maplemx/Agently#88]
There's a function missing here

![image](https://github.com/Maplemx/Agently/assets/72488598/2ea18229-61c7-4492-8fb5-864677ef377e)

**Comment by Maplemx** [comment]
It's because this chunk require no executor function so just skip the executor function definition. It works...

**Comment by Undertone0809** [comment]
Oh. It's a bit confusing the first time you see it, and it needs to be explained separately.
